### ISSUE TITLE
search is not wokring as expected

### ISSUE THREAD

**Issue by Subhraj07** [guyroyse/python-redis-examples#1]
I am getting the following error
ERR unknown command `FT.DROP`, with args beginning with: `bigfoot:sightings:search`

**Comment by guyroyse** [comment]
I reviewed this and found a bug, however not your bug. The call to FT.DROP failed because the index hadn't been created yet. So, I added code to check for the existence of the index before I tried to remove it. This is just so it can be execute multiple times.

My guess is that your error is not having the RediSearch module loaded. Did you run Redis via the `start-redis.sh` shell script included in this repo? If you are a Windows user, I apologize for not having something read to go for you but the shell script just has two Docker commands which should translate to Windows easily enough:

```
docker image pull redislabs/redismod

docker run \
  -p 6379:6379 \
  -v `pwd`/data:/data \
  redislabs/redismod \
  --save 60 1 \
  --loadmodule /usr/lib/redis/modules/redisearch.so \
  --dir /data \
  --requirepass foobared
```

Let me know if this helps resolve your problem.

Thanks!

**Comment by Subhraj07** [comment]
Hi, I did try the new code which you have updated but the issue is not resolved. and I  have installed Redis in Kubernetes. Do you have any suggestions on how can I configure the search module over there?

**Comment by guyroyse** [comment]
I can point you to some documentation but it depends on what image your using. Are you using one of the OSS ones from Dockerhub or are you using Redis Enterprise?

**Comment by Subhraj07** [comment]
HI,

I have deployed in kubernetes the following image : 
**redis alpine**

**Comment by guyroyse** [comment]
Modules are binaries that need to be added and configured in OSS Redis. There are images that have this already configured and ready to go. I'm not sure exactly what image "redis alpine" is but in 99% certain it doesn't have RediSearch loaded. Try using the [redismod](https://hub.docker.com/r/redislabs/redismod) image instead. It has all the main modules loaded and ready to go. That's the one my shell script is using.

**Comment by Subhraj07** [comment]
Thanks for the feeback. Will look into your suessions.
